[package]
name = "project1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
cgmath = "0.18.0"
log = "0.4.25"
png = "0.17.16"
pretty_env_logger = "0.5.0"
thiserror = "2.0.11"
vulkanalia = "0.26.0"
winit = "0.30.8"
